### ISSUE TITLE
Regexp error

### ISSUE THREAD

**Issue by rsolvang** [ugjka/B593s-22_SSH#1]
I have tried the binary for linux and also to build it myself, both giving me this error:
`Could not get tokens from maintainance page. Error: no regexp matches`
I'm using Arch btw 😉

**Comment by ugjka** [comment]
Post the system information from your router: http://192.168.1.1/html/status/systeminfo.asp
(Remove the IMEI number)

Could be a different model with different firmware and in that case there is nothing I can do...

My model:
```
Product Information
Model:
B593s-22
SN:
S2Z7S15624000308
Hardware version:
Ver.B
Firmware version:
V200R001B270D10SP00C00
Firmware build time:
Aug 20 2014 / 11:22:16

```

**Comment by rsolvang** [comment]
> Model: B593s-22
> SN: 866862020787590
> Hardware version: Ver.B
> Firmware version: V200R001B270D25SP02C07
> Firmware build time: Sep 19 2018 / 16:59:49

**Comment by ugjka** [comment]
Yeah, different firmware, nothing i can do about that. I'm gonna archive this project

**Comment by rsolvang** [comment]
Ok, thanks anyway :+1:
